name: Test

on: [push, pull_request]

jobs:
  unit:
    name: Unit
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest cli-test-helpers
          python -m pip install -e .
          python -c 'import sys; print(sys.version)'
          python -c 'import alfaci.version; print(alfaci.version.PKG_VERSION)'
      - name: Run pytest
        run: python -m pytest --color=yes
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage cli-test-helpers
          python -m pip install -e .
          python -c 'import sys; print(sys.version)'
          python -c 'import alfaci.version; print(alfaci.version.PKG_VERSION)'
      - name: Run pytest
        run: python -m coverage run -m pytest -v --color=yes
      - name: Display coverage report
        run: python -m coverage report -m
      - name: Generate xml coverage report
        run: python -m coverage xml
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest cli-test-helpers pylint flake8
          python -m pip install -e .
          python -c 'import sys; print(sys.version)'
          python -c 'import alfaci.version; print(alfaci.version.PKG_VERSION)'
      - name: Run pylint
        run: python -m pylint lib tests
      - name: Run flake8
        run: python -m flake8
  format:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install yapf
          python -m pip install -e .
          python -c 'import sys; print(sys.version)'
          python -c 'import alfaci.version; print(alfaci.version.PKG_VERSION)'
      - name: Run yapf
        run: python -m yapf -r -d lib tests
